spring:
  application:
    name: ${APPLICATION_NAME_DEV}
  servlet:
    multipart:
      enabled: true
      max-request-size: 5000MB
      max-file-size: 5000MB
  datasource:
    url: ${DB_CONNECTION_DEV}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        connection:
#          useUnicode: true
#          characterEncoding: utf8
#          characterSetResults: utf8mb4

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
server:
  port: 7890

logging:
   level:
     org:
       springframework:
          security: DEBUG

jwt:
  secret: ${JWT_SECRET_DEV}